// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNIsHtmtTQ0jrZ3bdtVQmsp5KXR17wiRo',
    appId: '1:660868529705:web:7a69c4afc221f89db06638',
    messagingSenderId: '660868529705',
    projectId: 'projetflutter-6711d',
    authDomain: 'projetflutter-6711d.firebaseapp.com',
    storageBucket: 'projetflutter-6711d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb3Eorv5DIHE8saJou9pMSVG7JgFSZKgY',
    appId: '1:660868529705:android:7abf5aca603d06aeb06638',
    messagingSenderId: '660868529705',
    projectId: 'projetflutter-6711d',
    storageBucket: 'projetflutter-6711d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYXC2nBffZI6ROXEX8nEKXpVs88AjcFnM',
    appId: '1:660868529705:ios:06f5d5eee4a98702b06638',
    messagingSenderId: '660868529705',
    projectId: 'projetflutter-6711d',
    storageBucket: 'projetflutter-6711d.appspot.com',
    iosClientId: '660868529705-f52cbebr56ir0692vgtd1rbfdo9nugas.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYXC2nBffZI6ROXEX8nEKXpVs88AjcFnM',
    appId: '1:660868529705:ios:06f5d5eee4a98702b06638',
    messagingSenderId: '660868529705',
    projectId: 'projetflutter-6711d',
    storageBucket: 'projetflutter-6711d.appspot.com',
    iosClientId: '660868529705-f52cbebr56ir0692vgtd1rbfdo9nugas.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFlutter',
  );
}
